# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: |
        npm install
        cd gui
        npm install
        cd ../server
        npm install
        cd ../common
        npm install
        cd ../tests-service
        npm install
        cd ..
    - name: Run Unit and Service Tests with Coverage
      run: |
        npm run server-start  &
        npm run test:badges
    - name: Commit the code coverage badge (if it changed)
      run: |
        DETATCHED_HEAD_FOUND=$(git status | grep 'HEAD detached' | wc -l)
        if [[ `git status --porcelain` && $DETATCHED_HEAD_FOUND -eq 0 ]]; then
          git add -A
          git commit -m "Autogenerated coverage badge"
          git push
        fi
